[2024-04-13T15:21:47.985+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: challenge_dag.extract_task manual__2024-04-13T15:21:44.130792+00:00 [queued]>
[2024-04-13T15:21:47.989+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: challenge_dag.extract_task manual__2024-04-13T15:21:44.130792+00:00 [queued]>
[2024-04-13T15:21:47.990+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-04-13T15:21:47.990+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-04-13T15:21:47.990+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-04-13T15:21:48.020+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): extract_task> on 2024-04-13 15:21:44.130792+00:00
[2024-04-13T15:21:48.024+0000] {standard_task_runner.py:55} INFO - Started process 34655 to run task
[2024-04-13T15:21:48.027+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'extract_task', 'manual__2024-04-13T15:21:44.130792+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpadfm7fhv']
[2024-04-13T15:21:48.030+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask extract_task
[2024-04-13T15:21:48.084+0000] {task_command.py:388} INFO - Running <TaskInstance: challenge_dag.extract_task manual__2024-04-13T15:21:44.130792+00:00 [running]> on host codespaces-3318c7
[2024-04-13T15:21:48.251+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=challenge_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2024-04-13T15:21:44.130792+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-13T15:21:44.130792+00:00
[2024-04-13T15:21:48.252+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-04-13T15:21:48.252+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://r2.datahub.io/clt989dvv0003l708h2jgh5ef/main/raw/data/constituents.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-extract-data.csv']
[2024-04-13T15:21:48.261+0000] {subprocess.py:86} INFO - Output:
[2024-04-13T15:21:48.266+0000] {subprocess.py:93} INFO - --2024-04-13 15:21:48--  https://r2.datahub.io/clt989dvv0003l708h2jgh5ef/main/raw/data/constituents.csv
[2024-04-13T15:21:48.277+0000] {subprocess.py:93} INFO - Resolving r2.datahub.io (r2.datahub.io)... 172.67.157.38, 104.21.40.221, 2606:4700:3030::ac43:9d26, ...
[2024-04-13T15:21:48.279+0000] {subprocess.py:93} INFO - Connecting to r2.datahub.io (r2.datahub.io)|172.67.157.38|:443... connected.
[2024-04-13T15:21:48.344+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 416 Range Not Satisfiable
[2024-04-13T15:21:48.344+0000] {subprocess.py:93} INFO - 
[2024-04-13T15:21:48.344+0000] {subprocess.py:93} INFO -     The file is already fully retrieved; nothing to do.
[2024-04-13T15:21:48.345+0000] {subprocess.py:93} INFO - 
[2024-04-13T15:21:48.345+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-13T15:21:48.382+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=challenge_dag, task_id=extract_task, execution_date=20240413T152144, start_date=20240413T152147, end_date=20240413T152148
[2024-04-13T15:21:48.442+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-04-13T15:21:48.458+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
