[2024-04-13T14:45:56.699+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: challenge_dag.load_task manual__2024-04-13T14:45:47.978794+00:00 [queued]>
[2024-04-13T14:45:56.704+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: challenge_dag.load_task manual__2024-04-13T14:45:47.978794+00:00 [queued]>
[2024-04-13T14:45:56.704+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-04-13T14:45:56.704+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-04-13T14:45:56.704+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-04-13T14:45:56.734+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): load_task> on 2024-04-13 14:45:47.978794+00:00
[2024-04-13T14:45:56.738+0000] {standard_task_runner.py:55} INFO - Started process 20850 to run task
[2024-04-13T14:45:56.741+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'load_task', 'manual__2024-04-13T14:45:47.978794+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmp7h0lwhyu']
[2024-04-13T14:45:56.742+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask load_task
[2024-04-13T14:45:56.792+0000] {task_command.py:388} INFO - Running <TaskInstance: challenge_dag.load_task manual__2024-04-13T14:45:47.978794+00:00 [running]> on host codespaces-3318c7
[2024-04-13T14:45:56.960+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=challenge_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2024-04-13T14:45:47.978794+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-13T14:45:47.978794+00:00
[2024-04-13T14:45:56.961+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-04-13T14:45:56.961+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ".separator ","\n.import --skip 1 /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv top_level_domains" | sqlite3 /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-load-db.db']
[2024-04-13T14:45:56.970+0000] {subprocess.py:86} INFO - Output:
[2024-04-13T14:45:56.976+0000] {subprocess.py:93} INFO - Columns renamed during .import /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv due to duplicates:
[2024-04-13T14:45:56.976+0000] {subprocess.py:93} INFO - "22" to "22_1",
[2024-04-13T14:45:56.977+0000] {subprocess.py:93} INFO - "22" to "22_2",
[2024-04-13T14:45:56.977+0000] {subprocess.py:93} INFO - "22" to "22_3",
[2024-04-13T14:45:56.977+0000] {subprocess.py:93} INFO - "22" to "22_4",
[2024-04-13T14:45:56.978+0000] {subprocess.py:93} INFO - "22" to "22_5",
[2024-04-13T14:45:56.978+0000] {subprocess.py:93} INFO - "22" to "22_6",
[2024-04-13T14:45:56.978+0000] {subprocess.py:93} INFO - "22" to "22_7"
[2024-04-13T14:45:57.038+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-13T14:45:57.069+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=challenge_dag, task_id=load_task, execution_date=20240413T144547, start_date=20240413T144556, end_date=20240413T144557
[2024-04-13T14:45:57.113+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-04-13T14:45:57.122+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
